### ISSUE TITLE
Error while loading time table

### ISSUE THREAD

**Issue by IgorSakharov** [maxkoshevoi/NureTimetableFlutter#11]
**Phone:**  Meizu M3 Note

**OS:**  Android 5.1

**Description:**
I just downloaded this app and go to page "Adding timetable". There I clicked on refresh button and get this error (look at the pic in attachments). I can not download any timetables, and do anything.

**Attachments:**
![IMAGE 2019-12-16 16:17:37](https://user-images.githubusercontent.com/24914717/70913895-9428d380-201f-11ea-8c40-d88446a219d7.jpg)

**Comment by maxkoshevoi** [comment]
Hi, thanks for downloading the app. Check your access to [http://cist.nure.ua](http://cist.nure.ua) (this is official source of all timetables). Try using mobile internet instead of WIFI to be able to access it.
